all:
  children:
    development:
      hosts:
        node02: {}
    loadbalancers:
      hosts:
        node01: {}
    testing:
      hosts:
        node01: {}
    webservers:
      children:
        production:
          hosts:
            node01: {}
            node02: {}
